name: Fly Deploy (Production)
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy production app
    runs-on: ubuntu-latest
    concurrency: deploy-group-prod
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly.prod.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_PROD }}
